import { useEffect, useState } from 'react'
import { ApiError, getLearningProfile, getRecommendations, type LearningProfile, type Recommendation, type Recommendations } from '../../lib/api'

type Props = { token: string; onStartMission: (missionId: string) => void }
const classificationLabel: Record<Recommendation['classification'], string> = { strong: 'STRONG', developing: 'DEVELOPING', weak: 'WEAK' }
function classificationStyle(classification: Recommendation['classification']) { return classification === 'strong' ? 'border-[rgba(58,155,141,0.48)] bg-[rgba(58,155,141,0.14)] text-[color:var(--primary)]' : classification === 'developing' ? 'border-[rgba(253,254,194,0.22)] bg-[rgba(253,254,194,0.08)] text-[color:var(--text)]' : 'border-[rgba(143,42,49,0.52)] bg-[rgba(143,42,49,0.16)] text-[#ffb0a8]' }
function Stat({ label, value, note }: { label: string; value: string; note: string }) { return <article className="border border-[rgba(253,254,194,0.12)] bg-[color:var(--panel)] p-4 shadow-[0_10px_30px_rgba(0,0,0,0.2)]"><p className="pixel-font text-[0.52rem] uppercase tracking-[0.14em] text-[color:var(--muted)]">{label}</p><p className="mt-3 text-2xl text-[color:var(--text)]">{value}</p><p className="mt-1 text-xs text-[color:var(--muted)]">{note}</p></article> }
function ConceptRow({ concept }: { concept: LearningProfile['concepts'][number] }) { return <article className="border border-[rgba(253,254,194,0.1)] bg-[rgba(0,0,0,0.12)] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-base text-[color:var(--text)]">{concept.concept}</h3><p className="mt-1 text-xs text-[color:var(--muted)]">{concept.attempted} attempted · {concept.correct} correct · {concept.incorrect} incorrect</p></div><span className={`border px-2 py-1 pixel-font text-[0.48rem] tracking-[0.12em] ${classificationStyle(concept.classification)}`}>{classificationLabel[concept.classification]}</span></div><div className="mt-4 flex items-center gap-3"><div className="h-2 flex-1 bg-[rgba(0,0,0,0.3)]"><div className="h-full bg-[color:var(--primary)]" style={{ width: `${concept.accuracy}%` }} /></div><span className="w-10 text-right text-sm text-[color:var(--text)]">{concept.accuracy}%</span></div></article> }
function RecommendationCard({ recommendation, onStartMission }: { recommendation: Recommendation; onStartMission: (missionId: string) => void }) { return <section className="border border-[rgba(58,155,141,0.48)] bg-[rgba(58,155,141,0.12)] p-5 shadow-[0_12px_32px_rgba(0,0,0,0.22)]"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="pixel-font text-[0.55rem] uppercase tracking-[0.14em] text-[color:var(--primary)]">Next focus</p><h2 className="mt-2 pixel-font text-base uppercase text-[color:var(--text)]">{recommendation.concept}</h2></div><span className="border border-[#ffb0a8] bg-[rgba(143,42,49,0.2)] px-2 py-1 pixel-font text-[0.48rem] tracking-[0.12em] text-[#ffb0a8]">{recommendation.priority} PRIORITY</span></div><p className="mt-4 max-w-2xl text-sm leading-6 text-[color:var(--muted)]">{recommendation.reason}</p><div className="mt-5 flex flex-wrap items-center justify-between gap-4 border-t border-[rgba(253,254,194,0.1)] pt-4"><div className="text-sm text-[color:var(--text)]">{recommendation.accuracy}% accuracy <span className="text-[color:var(--muted)]">· {classificationLabel[recommendation.classification]}</span></div>{recommendation.mission ? <div className="flex flex-wrap items-center gap-3"><span className="text-xs text-[color:var(--muted)]">Mission {recommendation.mission.missionNumber}: {recommendation.mission.title}</span><button className="min-h-10 border border-[rgba(58,155,141,0.7)] bg-[color:var(--primary)] px-4 pixel-font text-[0.56rem] uppercase tracking-[0.12em] text-[color:var(--text)]" onClick={() => onStartMission(recommendation.mission!.id)} type="button">Practice now</button></div> : <span className="text-xs text-[color:var(--muted)]">No suitable mission is available yet.</span>}</div></section> }

export function LearningDashboardPage({ token, onStartMission }: Props) {
  const [profile, setProfile] = useState<LearningProfile | null>(null); const [recommendations, setRecommendations] = useState<Recommendations | null>(null); const [error, setError] = useState('')
  useEffect(() => { let active = true; Promise.all([getLearningProfile(token), getRecommendations(token)]).then(([nextProfile, nextRecommendations]) => { if (active) { setProfile(nextProfile); setRecommendations(nextRecommendations) } }).catch((reason: unknown) => { if (active) setError(reason instanceof ApiError ? reason.message : 'Learning data is temporarily unavailable.') }); return () => { active = false } }, [token])
  if (error) return <main className="mx-auto min-h-screen max-w-5xl px-4 py-10"><section className="border border-[#ffb0a8] bg-[rgba(143,42,49,0.16)] p-5 text-sm text-[color:var(--text)]">{error}</section></main>
  if (!profile || !recommendations) return <main className="mx-auto min-h-screen max-w-5xl px-4 py-10"><p className="pixel-font text-xs uppercase tracking-[0.14em] text-[color:var(--primary)]">Loading learning profile...</p></main>
  const hasAttempts = profile.totalQuestionsAttempted > 0
  return <main className="mx-auto min-h-screen w-full max-w-[1200px] px-4 py-5 sm:px-6 lg:px-8"><header className="mb-6 border-b border-[rgba(253,254,194,0.1)] pb-5"><p className="pixel-font text-[0.58rem] uppercase tracking-[0.16em] text-[color:var(--primary)]">Operator intelligence</p><h1 className="mt-2 pixel-font text-xl uppercase leading-8 text-[color:var(--text)]">Learning dashboard</h1><p className="mt-2 text-sm text-[color:var(--muted)]">Performance, mastery, and the next useful mission.</p></header>{!hasAttempts ? <section className="border border-[rgba(253,254,194,0.14)] bg-[color:var(--panel)] p-6 shadow-[0_12px_32px_rgba(0,0,0,0.2)]"><p className="pixel-font text-xs uppercase tracking-[0.14em] text-[color:var(--primary)]">No performance data yet</p><h2 className="mt-3 pixel-font text-base uppercase">Your first run starts the profile.</h2><p className="mt-3 max-w-xl text-sm leading-7 text-[color:var(--muted)]">Complete a mission to build concept data, unlock targeted recommendations, and see where your debugging instincts are strongest. Recommendations will appear after your first answered mission.</p></section> : <><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Stat label="Questions attempted" value={`${profile.totalQuestionsAttempted}`} note="Total answers recorded" /><Stat label="Correct" value={`${profile.totalCorrect}`} note="Successful diagnoses" /><Stat label="Incorrect" value={`${profile.totalIncorrect}`} note="Signals to revisit" /><Stat label="Overall accuracy" value={`${profile.overallAccuracy}%`} note="Backend-calculated" /></section>{recommendations.nextFocus ? <div className="mt-6"><RecommendationCard recommendation={recommendations.nextFocus} onStartMission={onStartMission} /></div> : <section className="mt-6 border border-[rgba(58,155,141,0.48)] bg-[rgba(58,155,141,0.12)] p-5"><p className="pixel-font text-xs uppercase tracking-[0.14em] text-[color:var(--primary)]">All systems steady</p><p className="mt-3 text-sm text-[color:var(--muted)]">Every tracked concept is strong. Keep playing to maintain your edge.</p></section>}<section className="mt-6"><div className="mb-3 flex items-end justify-between gap-4"><div><p className="pixel-font text-[0.55rem] uppercase tracking-[0.14em] text-[color:var(--muted)]">Concept mastery</p><h2 className="mt-2 pixel-font text-sm uppercase">Where you stand</h2></div><span className="text-xs text-[color:var(--muted)]">{profile.concepts.length} concepts tracked</span></div><div className="grid gap-3 md:grid-cols-2">{profile.concepts.map((concept) => <ConceptRow concept={concept} key={concept.concept} />)}</div></section></>}</main>
}